name: Test OIDC

on:
  push:
    branches:
      - main
      - feature/*

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Verify Bucket
        run: aws s3 ls s3://${{ vars.S3_BUCKET }}