name: Frontend-CI
on:
  pull_request:
    branches: [main, develop]
env:
  NODE_VERSION: "22"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v6
      - name: Node setup
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Depndencies
        run: npm ci
      - name: Run Trivy Dependency Scan
        uses: trivy fs --severity HIGH,CRITICAL --exit-code 1 .
      - name: Run Eslint
        run: npm run lint
      